-- Enabling QS for demo DBs and clearing old QS data
USE master
GO
ALTER DATABASE [WideWorldImporters] SET QUERY_STORE = ON;
ALTER DATABASE [WideWorldImporters] SET QUERY_STORE CLEAR;
GO
ALTER DATABASE [WideWorldImporters] SET QUERY_STORE (
	OPERATION_MODE = READ_WRITE, 
	QUERY_CAPTURE_MODE = AUTO,   
	MAX_STORAGE_SIZE_MB = 2048,
	SIZE_BASED_CLEANUP_MODE = AUTO,
	DATA_FLUSH_INTERVAL_SECONDS = 60,
	INTERVAL_LENGTH_MINUTES = 5
	);
GO