-- Enabling QS for demo DBs and clearing old QS data
USE master
GO
-- Configuring QS with very low values
ALTER DATABASE [WideWorldImporters] SET QUERY_STORE (
	OPERATION_MODE = READ_WRITE, 
	QUERY_CAPTURE_MODE = ALL,  
	MAX_PLANS_PER_QUERY = 200,
	CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7),  
	MAX_STORAGE_SIZE_MB = 2,
	SIZE_BASED_CLEANUP_MODE = AUTO,
	DATA_FLUSH_INTERVAL_SECONDS = 1,
	INTERVAL_LENGTH_MINUTES = 1,
    WAIT_STATS_CAPTURE_MODE = OFF
	);
GO