apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hr-frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: hr-frontend
      tier: frontend
      track: stable
  replicas: 4 
  template:
    metadata:
      labels:
        app: hr-frontend
        tier: frontend
        track: stable
    spec:
      containers:
        - name: hr-frontend
          image: crobles10/hr-frontend:5.5
          ports:
            - containerPort: 80
          env:
            - name: SERVER
              value: 52.152.98.180
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
