version: "3"
services:
    parzival:
        build: ./parzival_db
        environment:
            SA_PASSWORD: "parzival_db_123"
            ACCEPT_EULA: "Y"
        ports:
            - "1533:1433"
        container_name: parzival
        hostname: parzival